-- Include available lua files in `lua/core` directory
require("core.settings")
require("core.folding")
require("core.keymaps")
require("core.auto_commands")
require("core.netrw")
require("core.treesitter")
require("core.lsp")
require("core.statusline")
require("core.neovide")
